---

- name: Create directories
  file:
    path: "/home/stack/{{ item }}"
    state: directory
    owner: stack
    group: stack
  with_items:
    - images
    - scripts
    - templates
    - utilities

- name: Copy images files locally
  unarchive:
    src: "/usr/share/rhosp-director-images/{{ item }}"
    dest: "/home/stack/images"
    remote_src: yes
  with_items:
    - "overcloud-full-latest-13.0.tar"
    - "ironic-python-agent-latest-13.0.tar"
  tags:
    - images

- name: Upload images
  shell: |
    source /home/stack/stackrc
    openstack overcloud image upload --image-path /home/stack/images/
  tags:
    - images

- name: Stat the instackenv.json file
  stat:
    path: "files/instackenv.json"
  register: instackenv
  delegate_to: localhost

- debug: var=instackenv

- name: Import and configure based on instackenv.json
  block:
    - copy:
        src: files/instackenv.json
        dest: /home/stack/instackenv.json
        owner: "stack"
        group: "stack"
        remote_src: no
      tags:
        - nodes

    - shell: |
        source /home/stack/stackrc
        openstack overcloud node import /home/stack/instackenv.json
      tags:
        - nodes
        - import_nodes

    - shell: |
        source /home/stack/stackrc
        openstack baremetal node list -f json
      register: baremetal_nodes
      tags:
        - nodes
        - introspection

    - name: Introspect nodes from imported instackenv.json
      shell: |
        source /home/stack/stackrc
        openstack overcloud node introspect --all-manageable --provide
      when:
        - ( baremetal_nodes.stdout_lines | length ) == 0
      register: introspection_complete

    - name: Generate list of nodes to introspect
      set_fact: nodes_to_introspect="{{ nodes_to_introspect|default([]) + [ item.UUID ] }}"
      when:
        - item['Provisioning State'] == 'manageable'
        - introspection_complete.skipped == True
      with_items:
        - "{{ baremetal_nodes.stdout | from_json }}"

    - name: Introspect nodes
      shell: |
        source /home/stack/stackrc
        openstack overcloud node introspect {{ nodes_to_introspect | join(" ") }} --provide
      tags:
        - nodes
        - introspection
      when:
        - nodes_to_introspect is defined
        - nodes_to_introspect > 0
  when:
     instackenv.stat.exists == True

- name: Update DNS setting for ctlplane-subnet
  shell: |
     source /home/stack/stackrc
     openstack subnet set --dns-nameserver {{ undercloud_name_servers | join( " --dns-nameserver " ) }} ctlplane-subnet
  ignore_errors: yes
  tags:
    - dns

- name: Get List of all flavors
  shell: | 
     source /home/stack/stackrc
     openstack flavor list -f value -c Name
  register: flavor_list 
  tags:
    - flavor_update 

- name: Update Flavors for uefi
  shell: | 
     source /home/stack/stackrc
     openstack flavor set --property capabilities:boot_mode='uefi' {{ item }}
  with_items:
    - "{{ flavor_list.stdout_lines }}"
  tags: 
    - flavor_update
  when: undercloud_uefi_flavors | bool   
