---

- name: Install templates 
  block:
  - name: Copy over overcloud templates
    copy:
      src: "overcloud_templates/"
      dest: "/home/stack/templates"
 
  - name: Create any missing template directories
    file:
      path: "/home/stack/templates/{{ item.path }}"
      state: directory
    with_filetree: "templates"
    when:
      - item.state == 'directory'
  
  - name: Create templates
    template:
      src: "{{ item.src }}"
      dest: "/home/stack/templates/{{ item.path | regex_replace('.j2', '') }}"
    with_filetree: "templates"
    when:
      - item.state == 'file'
  tags:
  - overcloud
  - overcloud_templates

- name: Create deploy_overcloud.sh script
  template:
    src: scripts/deploy_overcloud.sh.j2
    dest: /home/stack/scripts/deploy_overcloud.sh
    mode: 0755
  tags:
   - scripts
